name: Test Dynamic Needs with Awareness

on:
  push:
  workflow_dispatch:
    inputs:
      run_job_b:
        description: "Run Job B?"
        required: true
        default: "no"

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Step A
        run: echo "Running Job A ${{vars.NAME}}"

  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    if: ${{ github.event.inputs.run_job_b == 'yes' }}
    outputs:
      did_run: 'true'
    steps:
      - name: Step B
        run: echo "Running Job B"

  jobC:
    runs-on: ubuntu-latest
    needs: jobB
    if: ${{ github.event.inputs.run_job_b == 'yes' }}
    outputs:
      did_run: 'true'
    steps:
      - name: Step B
        run: echo "Running Job B"

  finalJob:
    needs: [jobA, jobB]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Detect if Job B Ran
        run: |
          if [[ "${{ needs.jobB.result }}" == "success" ]]; then
            echo "✅ Job B ran successfully"
          elif [[ "${{ needs.jobB.result }}" == "skipped" ]]; then
            echo "⏭️ Job B was skipped"
          else
            echo "❌ Job B did not complete successfully"
          fi

      - name: Final Step
        run: echo "Final job logic runs regardless."
